module.exports = (sequelize, DataTypes) => {
    return sequelize.define(
        'Drivers',
        {
            driverId: {
                type: DataTypes.INTEGER,
                allowNull: false,
                field: "driverId",
                primaryKey: true,
                autoIncrement: true,
                searchable: true,
                alias: "Driver ID",
                aliasValue: "driverId",
            },
            firstName: {
                type: DataTypes.STRING,
                allowNull: false,
                field: "firstName",
                searchable: true,
                alias: "First Name",
                aliasValue: "firstname",
            },
            lastName: {
                type: DataTypes.STRING,
                allowNull: false,
                field: "lastName",
                searchable: true,
                alias: "Last Name",
                aliasValue: "lastname",
            },
            fullName: { // Concatenated on insert to match firstname and lastname
                type: DataTypes.STRING,
                allowNull: false,
                field: "fullName",
                searchable: true,
                alias: "Full Name",
                aliasValue: "fullname",
            },
            insuranceId: {
                type: DataTypes.INTEGER,
                allowNull: false,
                field: "insuranceId",
                searchable: true,
                alias: "Driver Insurance Id",
                aliasValue: "insuranceid",
            },
            phoneNumber: {
                type: DataTypes.STRING,
                field: "phoneNumber",
                searchable: true,
                alias: "Phone Number",
                aliasValue: "phonenumber",
            },
            address: {
                type: DataTypes.STRING,
                field: "address",
                searchable: true,
                alias: "Driver Address",
                aliasValue: "driveraddress",
            },
            notes: {
                type: DataTypes.STRING,
                field: "notes",
                searchable: true,
                alias: "Driver Notes",
                aliasValue: "drivernotes",
            },
            createdAt: {
                type: DataTypes.DATE,
                field: "createdAt",
                searchable: true,
                alias: "Created At",
                aliasValue: "createdat",
            },
            updatedAt: {
                type: DataTypes.DATE,
                field: "updatedAt",
                searchable: true,
                alias: "Updated At",
                aliasValue: "updatedat",
            },
        },
        {
            tableName: "Drivers",
            timestamps: false,
        },
    )
};